---

# REQUIRED Settings -------------------------------------------------------------------------------

# REQUIRED: hostname running
 proxmox_host: pve
 proxmox_node: pve
 proxmox_ct_name: BIND
 proxmox_vm_name: ANSIBLE
 proxmox_autostart: no

# REQUIRED: API user for connecting to host
 proxmox_api_user: ansible@pve

# REQUIRED: password of API user
 proxmox_api_password: ansible

# REQUIRED: define numeric ID
 proxmox_vmid: "124"

# REQUIRED: IP to use for proxmox VM/CT
 proxmox_ip: 172.18.60.140
 proxmox_ip_mask: 24

# REQUIRED: gateway to use for VM/CT setup
 proxmox_network_gateway: 172.18.60.1

# REQUIRED: template to use for provisioning
 proxmox_ostemplate: local:vztmpl/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz
 proxmox_vm_iso: local:iso/ubuntu-20.04.2-live-server-amd64.iso 

# REQUIRED: The authorized keys to add for the root user.
 proxmox_authorized_keys_root: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWHPsprntbVVSOkakF2qMift9R+oRRxwEKeaR8mlr/Xt+cevikVpov3Q10h17xzje6+IDW8kZHsWbqBUnMHacEcRxY9avA1FO89yfDWI1QUeltdHRy0ou3+9Q0KgQUkI1rBr+M1npJPVEddv2Y6YctwFdpc+e3j3MrFvfWt5bb6lCPKq7JrX+sJhcWE7xk5A+6+RUPZtOo8a/6Q7giW6hVhX5G44IuL0CsuxB0Z9tzK7VP9f2lft2N/c3NNSDOBOuXFikCC3wnt8mTwy2HzDC3wxme6CMrlVe33MQx4mYuWl/02vWa364FnTSF7LGva0qs6S1WWB+RuIQEAthXs1VD PROXMOX"

# REQUIRED: The password to set for the root user.
 proxmox_password_root: ricardo

# Important Settings (you might want to override these) -------------------------------------------
 proxmox_type: container

# Main memory in MB.
 proxmox_memory: 2048

# Disk space/quota in GB.
 proxmox_disk: "4"
 proxmox_disk_size: "15"

# Cores to allocate.
 proxmox_cores: 1

# CPUs to allocate.
 proxmox_cpus: 1
 proxmox_sockets: 2

# Whether or not to allow for running Docker inside container (requires priviledged container
# if CT).
 proxmox_enable_docker: false

# Custom bash script to execute in container, e.g., for proxy setup.
 proxmox_container_custom_script: ""

# Other Settings (the defaults are sensible for most cases) ---------------------------------------

# MAC address of proxmox network.
 proxmox_hwaddr: "{{ '52:54:00' | random_mac }}"

# Storage system to use
 proxmox_storage: ceph

# Whether to start CT/VM on host boot.
 proxmox_onboot: true

# Any secondary mounts.
 proxmox_secondary_mounts: {}

# The bridge to use for containers.
 proxmox_network_bridge: vmbr0
 proxmox_bridge_tag: 60
 proxmox_vm_network_model: virtio

# How long to sleep before first pct exec command.
 proxmox_container_sleep: 60s
